version: '2'
services:
    bagle-db:
        image: mvertes/alpine-mongo
        restart: always
        ports: 
         - "27017"
    bagle-app:
        image: abbabalagan/bagle-challenge-box
        restart: always
        ports: 
         - "80:3000"
        links: 
         - 'bagle-db'