version: '2'
services:
    bagle-db:
        container_name: bagle-db
        image: mvertes/alpine-mongo
        restart: always
        ports: 
         - 27017
    bagle-app:
        container_name: bagle-app
        image: abbabalagan/bagle-challenge-box
        restart: always
        expose: 
         - "3000"
        links: 
         - 'bagle-db'
         - nginx
        environment:
         VIRTUAL_HOST: 'localhost'
    nginx: 
        image: jwilder/nginx-proxy
        container_name: production_nginx
        volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf
          - "/var/run/docker.sock:/tmp/docker.sock:ro"
        ports:
          - 80:80